apiVersion: v1
kind: Pod
metadata:
  name: work
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: mydir
      mountPath: /homework
    lifecycle:
     preStop:
       exec:
         command: ["rm", "-f", "/homework/index.html"]
  # These container get index.html
  initContainers:
  - name: init-container
    image: busybox
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch/
    volumeMounts:
    - name: mydir
      mountPath: /init
  volumes:
  - name: mydir
    emptyDir: {}