apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuber-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
