repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

helmDefaults:
  atomic: true
  timeout: 300
  wait: true

releases:
  - name: kafka-dev
    namespace: dev
    version: 28.0.3
    chart: bitnami/kafka
    values:
      - kafka-dev-values.yaml
  - name: kafka-prod
    namespace: prod
    version: 28.0.3
    chart: bitnami/kafka
    values:
      - kafka-prod-values.yaml
